"use client";
import { useState } from "react";
import { Badge, Empty } from "./admin-ui";
import { Booking, Unit, labels, money, date, viewLabels } from "./admin-types";
export const timestamp = (value?: string) => value ? new Date(value).toLocaleString("vi-VN", { timeZone: "Asia/Ho_Chi_Minh" }) : "—";
function Info({ rows }: { rows: [string, React.ReactNode][] }) { return <dl className="admin-record-info">{rows.map(([name, value]) => <div key={name}><dt>{name}</dt><dd>{value === "" || value == null ? "—" : value}</dd></div>)}</dl>; }
export function UnitDetails({ unit: u }: { unit: Unit }) {
  return <><div className="admin-record-header"><div><small>{u.property?.name} / {u.publicCode}</small><h3>{u.nameVi}</h3><p>{u.nameEn}</p></div><Badge value={u.status}/></div><div className="admin-detail-grid"><section><h4>Thông tin căn hộ</h4><Info rows={[["Mã nội bộ", u.internalCode], ["Phòng ngủ / phòng tắm", `${u.bedroomCount} / ${Number(u.bathroomCount)}`], ["Số giường", u.bedCount], ["Sức chứa", `${u.maxGuests} khách`], ["Diện tích", `${Number(u.area)} m²`], ["Hướng nhìn", u.viewType ? (viewLabels[u.viewType] ?? u.viewType) : "Chưa xác định"]]}/></section><section><h4>Giá & thanh toán</h4><Info rows={[["Giá mỗi đêm", money(u.basePrice, u.currency)], ["Phí dọn dẹp", money(u.cleaningFee, u.currency)], ["Phí dịch vụ", `${Number(u.serviceFeeRate) * 100}%`], ["Cọc yêu cầu", `${Number(u.depositRate) * 100}%`], ["Ngày tạo", timestamp(u.createdAt)], ["Cập nhật cuối", timestamp(u.updatedAt)]]}/></section></div><section className="admin-detail-section"><h4>Tiện ích</h4><div className="admin-tag-list">{u.amenities?.length ? u.amenities.map(a => <span key={a.amenityId}>{a.amenity.nameVi}</span>) : <p>Chưa cấu hình tiện ích.</p>}</div></section><section className="admin-detail-section"><h4>Mô tả tiếng Việt</h4><p className="admin-preserve-text">{u.descriptionVi || "Chưa có mô tả."}</p><h4>Mô tả tiếng Anh</h4><p className="admin-preserve-text">{u.descriptionEn || "Chưa có mô tả."}</p></section></>;
}
export function BookingDetails({ booking: b }: { booking: Booking }) {
  const [tab, setTab] = useState("overview");
  return <><div className="admin-record-header"><div><small>{labels[b.source] ?? b.source} · Tạo lúc {timestamp(b.createdAt)}</small><h3>{b.customer.lastName} {b.customer.firstName}</h3><p>{b.unit.nameVi} · {b.guestCount} khách</p></div><Badge value={b.status}/></div><div className="admin-tabs"><button className={tab === "overview" ? "active" : ""} onClick={() => setTab("overview")}>Thông tin booking</button><button className={tab === "payments" ? "active" : ""} onClick={() => setTab("payments")}>Giao dịch <b>{b.payments.length}</b></button></div>{tab === "overview" ? <><div className="admin-detail-grid"><section><h4>Khách hàng & lưu trú</h4><Info rows={[["Điện thoại", b.customer.phone], ["Email", b.customer.email], ["Quốc tịch", b.customer.nationality], ["Ngày nhận phòng", date(b.checkIn)], ["Ngày trả phòng", date(b.checkOut)], ["Thời gian lưu trú", `${Math.round((+new Date(b.checkOut) - +new Date(b.checkIn)) / 86400000)} đêm`], ["Nguồn đặt", labels[b.source] ?? b.source]]}/></section><section><h4>Chi tiết thanh toán</h4><Info rows={[["Tiền phòng", money(b.subtotal, b.currency)], ["Phụ phí", money(b.fees, b.currency)], ["Giảm giá", money(b.discount, b.currency)], ["Tổng thanh toán", <strong key="total">{money(b.total, b.currency)}</strong>], ["Cọc yêu cầu", money(b.depositRequired, b.currency)], ["Đã thanh toán", money(b.paidAmount, b.currency)], ["Còn phải thu", <strong key="due">{money(b.remainingAmount, b.currency)}</strong>]]}/></section></div><section className="admin-detail-section"><h4>Ghi chú hồ sơ khách hàng</h4><p className="admin-preserve-text">{b.customer.notes || "Chưa có ghi chú."}</p><p className="admin-form-note">Cập nhật cuối: {timestamp(b.updatedAt)}</p></section></> : b.payments.length ? <div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Giao dịch</th><th>Phương thức</th><th>Số tiền</th><th>Trạng thái</th></tr></thead><tbody>{b.payments.map(p => <tr key={p.id}><td><b>{labels[p.type] ?? p.type}</b><small>{timestamp(p.paidAt ?? p.createdAt)}</small><small>{p.providerReference || p.id}</small></td><td>{labels[p.method] ?? p.method}</td><td>{money(p.amount, p.currency)}</td><td><Badge value={p.status}/></td></tr>)}</tbody></table></div> : <Empty text="Chưa có giao dịch" detail="Các khoản thu sẽ xuất hiện sau khi được ghi nhận."/>}</>;
}
