"use client";
import { useState } from "react";
import { Building2, Pencil, Plus, Users } from "lucide-react";
import { Customer, Unit, Payment, labels, money, date } from "./admin-types";
import { Badge, DataState, Empty, ExportButton, FormModal, Heading, Toolbar, exportCsv, useData } from "./admin-ui";
import { useAdmin } from "./admin-shell";
export function CustomerManager() {
  const query = useData<Customer[]>("customers"), { permissions } = useAdmin(); const [search, setSearch] = useState(""), [edit, setEdit] = useState<Customer | "new">();
  const rows = (query.data ?? []).filter(c => `${c.firstName} ${c.lastName} ${c.email} ${c.phone}`.toLowerCase().includes(search.toLowerCase()));
  const c = edit === "new" ? undefined : edit;
  return <><Heading title="Khách hàng" description="Ghi nhớ thông tin, chăm sóc tốt hơn mỗi lần quay lại." action={permissions.includes("customer.create") && <button className="admin-button" onClick={() => setEdit("new")}><Plus size={17}/>Thêm khách hàng</button>}/><section className="admin-panel"><Toolbar search={search} setSearch={setSearch}/><DataState {...query}>{rows.length ? <div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Khách hàng</th><th>Liên hệ</th><th>Số booking</th><th>Ghi chú</th><th/></tr></thead><tbody>{rows.map(c => <tr key={c.id}><td><div className="admin-cell-person"><span className="admin-avatar"><Users size={17}/></span><b>{c.lastName} {c.firstName}</b></div></td><td>{c.phone}<small>{c.email || "Chưa có email"}</small></td><td>{c._count?.bookings ?? 0} lượt đặt</td><td className="admin-wrap">{c.notes || "—"}</td><td>{permissions.includes("customer.update") && <button className="admin-icon-button" aria-label="Sửa khách hàng" onClick={() => setEdit(c)}><Pencil size={16}/></button>}</td></tr>)}</tbody></table></div> : <Empty/>}<div className="admin-pagination">{rows.length} khách hàng · Hiển thị tối đa 1.000 hồ sơ gần nhất</div></DataState></section>{edit && <FormModal title={c ? "Cập nhật khách hàng" : "Thêm khách hàng"} path={c ? `customers/${c.id}` : "customers"} method={c ? "PATCH" : "POST"} close={() => setEdit(undefined)} saved={query.reload} fields={[{ name: "lastName", label: "Họ", value: c?.lastName }, { name: "firstName", label: "Tên", value: c?.firstName }, { name: "phone", label: "Điện thoại", type: "tel", value: c?.phone, minLength: 5 }, { name: "email", label: "Email", type: "email", required: false, value: c?.email }, { name: "notes", label: "Ghi chú chăm sóc", required: false, value: c?.notes }]}/>}</>;
}
export function UnitManager({ pricing = false }: { pricing?: boolean }) {
  const query = useData<Unit[]>("units"), { permissions } = useAdmin(); const [search, setSearch] = useState(""), [edit, setEdit] = useState<Unit>();
  const canEdit = ["unit.update", "pricing.update", "unit.publish"].every(p => permissions.includes(p));
  const rows = (query.data ?? []).filter(u => `${u.nameVi} ${u.publicCode}`.toLowerCase().includes(search.toLowerCase()));
  return <><Heading title={pricing ? "Giá phòng" : "Danh mục căn hộ"} description={pricing ? "Quản lý giá cơ bản mỗi đêm. Báo giá booking áp dụng thêm phụ phí và giá theo ngày đã cấu hình." : "Một góc nhìn đầy đủ về không gian lưu trú của bạn."}/><section className="admin-panel"><Toolbar search={search} setSearch={setSearch}/><DataState {...query}>{rows.length ? <div className="admin-unit-grid">{rows.map(u => <article className="admin-unit-card" key={u.id}><div className="admin-unit-cover"><Building2 size={44} strokeWidth={1}/><span>{u.publicCode}</span><Badge value={u.status}/></div><div className="admin-unit-info"><small>{u.property?.name}</small><h2>{u.nameVi}</h2><p>{u.bedroomCount} phòng ngủ <i/> {u.maxGuests} khách <i/> {Number(u.area)} m²</p><div><strong>{money(u.basePrice, u.currency)}<small> / đêm</small></strong>{canEdit && <button className="admin-icon-button" aria-label={`Sửa ${u.nameVi}`} onClick={() => setEdit(u)}><Pencil size={17}/></button>}</div></div></article>)}</div> : <Empty/>}</DataState></section>{edit && <FormModal title="Cập nhật căn hộ & giá" path={`units/${edit.id}`} method="PATCH" close={() => setEdit(undefined)} saved={query.reload} fields={[{ name: "nameVi", label: "Tên căn hộ", value: edit.nameVi }, { name: "basePrice", label: `Giá cơ bản / đêm (${edit.currency})`, type: "number", min: 0, value: Number(edit.basePrice) }, { name: "maxGuests", label: "Số khách tối đa", type: "number", min: 1, max: 100, value: edit.maxGuests }, { name: "status", label: "Trạng thái mở bán", value: edit.status, options: ["DRAFT", "PUBLISHED", "TEMP_UNAVAILABLE", "INACTIVE", "ARCHIVED"].map(value => ({ value, label: labels[value] })) }]}/>}</>;
}
export function PaymentManager() {
  const query = useData<Payment[]>("payments"); const [search, setSearch] = useState(""); const rows = (query.data ?? []).filter(p => `${p.booking?.bookingCode} ${p.method} ${labels[p.status]}`.toLowerCase().includes(search.toLowerCase()));
  return <><Heading title="Thanh toán & đối soát" description="Theo dõi tiền cọc, thanh toán và lịch sử giao dịch. Ghi nhận tiền tại chi tiết booking." action={<ExportButton run={() => exportCsv("thanh-toan", [["Booking", "Ngày", "Số tiền", "Tiền tệ", "Phương thức", "Trạng thái"], ...rows.map(p => [p.booking?.bookingCode ?? "", date(p.createdAt), p.amount, p.currency, p.method, labels[p.status] ?? p.status])])}/>}/><section className="admin-panel"><Toolbar search={search} setSearch={setSearch}/><DataState {...query}>{rows.length ? <div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Booking</th><th>Ngày ghi nhận</th><th>Phương thức</th><th>Loại</th><th>Số tiền</th><th>Trạng thái</th></tr></thead><tbody>{rows.map(p => <tr key={p.id}><td><b>{p.booking?.bookingCode}</b></td><td>{date(p.createdAt)}</td><td>{labels[p.method] ?? p.method}</td><td>{labels[p.type] ?? p.type}</td><td><b>{money(p.amount, p.currency)}</b></td><td><Badge value={p.status}/></td></tr>)}</tbody></table></div> : <Empty/>}<div className="admin-pagination">{rows.length} giao dịch · Tối đa 1.000 giao dịch gần nhất</div></DataState></section></>;
}
type Property = { id: string; name: string; address: string; status: string; checkInTime: string; checkOutTime: string; _count: { units: number } };
export function PropertyManager() { const query = useData<Property[]>("properties"); return <><Heading title="Cơ sở lưu trú" description="Thông tin các tòa nhà và quy định nhận, trả phòng."/><DataState {...query}><div className="admin-unit-grid">{query.data?.map(p => <section className="admin-panel admin-property" key={p.id}><Building2 size={30}/><Badge value={p.status}/><h2>{p.name}</h2><p>{p.address}</p><dl className="admin-summary"><div><dt>Số căn hộ</dt><dd>{p._count.units}</dd></div><div><dt>Giờ nhận / trả phòng</dt><dd>{p.checkInTime} / {p.checkOutTime}</dd></div></dl></section>)}</div>{!query.data?.length && <Empty/>}</DataState></>; }
type Audit = { id: string; action: string; entityType: string; entityId: string; actorUserId: string; createdAt: string; metadata?: Record<string, unknown> };
export function AuditManager() { const query = useData<Audit[]>("audit"), [search, setSearch] = useState(""); const rows = (query.data ?? []).filter(a => `${a.action} ${a.entityType} ${a.entityId} ${a.actorUserId}`.toLowerCase().includes(search.toLowerCase())); return <><Heading title="Nhật ký hoạt động" description="Dấu vết thao tác để kiểm tra và đối soát. Hiển thị 500 hoạt động gần nhất."/><section className="admin-panel"><Toolbar search={search} setSearch={setSearch}/><DataState {...query}>{rows.length ? <div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Thời gian</th><th>Thao tác</th><th>Đối tượng</th><th>Người thực hiện</th><th>Chi tiết</th></tr></thead><tbody>{rows.map(a => <tr key={a.id}><td>{new Date(a.createdAt).toLocaleString("vi-VN")}</td><td><b>{a.action}</b></td><td>{a.entityType}<small>{a.entityId}</small></td><td>{a.actorUserId || "Hệ thống"}</td><td className="admin-wrap">{a.metadata ? JSON.stringify(a.metadata) : "—"}</td></tr>)}</tbody></table></div> : <Empty/>}</DataState></section></>; }
